@startuml

package N1215\Http\Router {

    interface RoutingErrorInterface {
        + getStatusCode(): int
        + getMessage(): string
    }

    class RoutingError {
        - $statusCode: int
        - $message: string
        + getStatusCode(): int
        + getMessage(): string
    }

    interface RoutingResultInterface {
        + isSuccess(): bool;
        + getMatchedHandler(): ?RequestHandlerInterface;
        + getMatchedParams(): array;
        + getError(): ?RoutingErrorInterface;
    }

    interface RoutingErrorResponderInterface {
        + respond(ServerRequestInterface $request, RoutingErrorInterface $error): ResponseInterface
    }
    note bottom of RoutingErrorResponderInterface: Converts routing error to PSR-7 response

    RoutingResultInterface o- RoutingErrorInterface

    RoutingErrorInterface --> RoutingErrorResponderInterface: input
    Psr\Http\Message.ServerRequestInterface --> RoutingErrorResponderInterface: input
    RoutingErrorResponderInterface --> Psr\Http\Message.ResponseInterface: output

    RoutingError --|> RoutingErrorInterface: implements

}

namespace Psr\Http\Message {
    interface ServerRequestInterface
    interface ResponseInterface
}

@enduml